/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Gergely' at '9/23/16 11:59 AM' with Gradle 2.1
 *
 * @author Gergely, @date 9/23/16 11:59 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
